//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEDollController.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEDollController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0,-4} {1,-6} {2} 的本地化字符串。
        /// </summary>
        internal static string Commands_Dump_Format {
            get {
                return ResourceManager.GetString("Commands.Dump.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #    Size   Client
        ///----+------+--------------------------- 的本地化字符串。
        /// </summary>
        internal static string Commands_Dump_Header {
            get {
                return ResourceManager.GetString("Commands.Dump.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dump #{0} from client &quot;{1}&quot; ({2} bytes), under format &quot;{3}&quot;:
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Dump_Title {
            get {
                return ResourceManager.GetString("Commands.Dump.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breaks or continues the process&apos;s execution.
        ///
        ///break
        ///
        ///This command toggles the execution state between running and suspended.
        ///For a newly-created Doll process, it&apos;s state is running.
        ///For a newly-attached Doll process, it&apos;s state is suspended.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Break {
            get {
                return ResourceManager.GetString("Commands.Help.Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a new Doll client by creating or attaching to a process.
        ///
        ///doll CMDLINE
        ///doll --attach PID
        ///
        ///CMDLINE		Create a new process by running CMDLINE.
        ///PID		Attach to process PID.
        ///		Use `ps` to get the list of available PIDs.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Doll {
            get {
                return ResourceManager.GetString("Commands.Help.Doll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays or saves dumped data.
        ///
        ///dump
        ///dump ID [--format=FORMAT] [--save=SAVEFILE]
        ///
        ///Type `hook` without any arguments displays a list of dumped data.
        ///
        ///ID		ID of the dump to operate.
        ///FORMAT		Show or save data under FORMAT. Possible formats are:
        ///		hex(default), raw, ansi, unicode, utf8, x86, x64
        ///SAVEFILE	Save the data to SAVEFILE instead of displaying them.
        ///		SAVEFILE will be overwritten if it exists.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Dump {
            get {
                return ResourceManager.GetString("Commands.Help.Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends the client, stopping its process.
        ///
        ///end
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_End {
            get {
                return ResourceManager.GetString("Commands.Help.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluates a expression on current context.
        ///
        ///eval EXPR
        ///
        ///EXPR		The expression to be evaluated.
        ///
        ///An &quot;expression&quot; is a C# expression embraced with braces, e.g. {(uint)poi(ax)+4}
        ///
        ///The types, methods and fields from namespaces &quot;System&quot; and &quot;System.Linq&quot;,
        ///among with the following, are provided:
        ///
        ///(type alias) word
        ///	A integer of the native word size (`int` on x86 or `long` on x64).
        ///(type alias) uword
        ///	Similar to `word` but unsigned.
        ///string str(uword PTR)
        ///	Returns the C-style string PTR points to.
        ///st [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Eval {
            get {
                return ResourceManager.GetString("Commands.Help.Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quits the Controller, end all connected clients.
        ///
        ///exit
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Exit {
            get {
                return ResourceManager.GetString("Commands.Help.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides help information for commands.
        ///
        ///help [COMMAND]
        ///
        ///COMMAND		Display help information for command COMMAND.
        ///		If omitted, display a list of available commands.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Help {
            get {
                return ResourceManager.GetString("Commands.Help.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installs a new hook and set its actions.
        ///
        ///hook
        ///hook {[MODULE!]SYMBOL|0xADDR|*PATTERN}
        ///     [--convention=CONVENTION] [--stack=STACK[,RETURN]]
        ///     [--before [ACTION ...]] [--after [ACTION ...]]
        ///
        ///Type `hook` without any arguments displays a list of hooks.
        ///Call `hook` on an existing hook will overwrite its convention and actions.
        ///
        ///MODULE		The target module to search for symbol NAME.
        ///		If omitted, default to the first module containing symbol NAME.
        ///SYMBOL		The function&apos;s symbol name (e.g. WinExec o [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Hook {
            get {
                return ResourceManager.GetString("Commands.Help.Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminates process(es) with PID or name.
        ///
        ///kill PID
        ///kill --all NAME
        ///
        ///PID		The PID of the process to be terminated.
        ///		Use `ps` to get the list of available PIDs.
        ///NAME		Terminate all processes with name NAME.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Kill {
            get {
                return ResourceManager.GetString("Commands.Help.Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts to listen for clients and displays addresses listening on.
        ///
        ///listen [--ipv6] [PORT]
        ///
        ///--ipv6		Listens on IPv6 interfaces, instead of IPv4 ones.
        ///PORT		The listening port. Default to 31415.
        ///
        ///This command may successfully execute only once; any subsequent call will fail.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Listen {
            get {
                return ResourceManager.GetString("Commands.Help.Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executes commands from a script.
        ///
        ///load SCRIPT [ARGUMENTS ...]
        ///
        ///SCRIPT		The script file to execute.
        ///		If embraced with double-quotes, SCRIPT is treated as a path;
        ///		otherwise, SCRIPT is the name (w/ or w/o extension) of a script
        ///		in &quot;Scripts&quot; folder (preferred) or &quot;Scripts\API&quot; folder.
        ///ARGUMENTS	Arguments passed to the script.
        ///		The arguments will be inserted into any command in the script,
        ///		given the command ends with a single `*`.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Load {
            get {
                return ResourceManager.GetString("Commands.Help.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loads a module into the process&apos;s address space.
        ///
        ///loaddll MODULE
        ///
        ///MODULE		The module path passed to LoadLibrary().
        ///
        ///Internally, `loaddll` calls LoadLibrary() on a new thread.
        ///Call `loaddll` with libDoll will cause nothing but must never be attempted.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_LoadDll {
            get {
                return ResourceManager.GetString("Commands.Help.LoadDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays a list of running processes.
        ///
        ///ps
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Ps {
            get {
                return ResourceManager.GetString("Commands.Help.Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records comments (remarks) in a script file.
        ///
        ///rem [...]
        ///#[...]
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Rem {
            get {
                return ResourceManager.GetString("Commands.Help.Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts a instance of command interpreter (%COMSPEC%, usually CMD.EXE).
        ///
        ///shell [ARGUMENTS ...]
        ///
        ///ARGUMENTS	Arguments passed to %COMSPEC%.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Shell {
            get {
                return ResourceManager.GetString("Commands.Help.Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets the target client.
        ///
        ///target [ID]
        ///target --doll
        ///target --monitor
        ///
        ///ID		The new target client&apos;s ID.
        ///		If omitted, displays a list of connected clients.
        ///--doll		Set target to last targeted Doll client.
        ///--monitor	Set target to last targeted Monitor client.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Target {
            get {
                return ResourceManager.GetString("Commands.Help.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unhook ID
        ///
        ///ID		ID of the hook.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Unhook {
            get {
                return ResourceManager.GetString("Commands.Help.Unhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 verdict {approve|reject|terminate}
        ///
        ///approve		Continue the execution.
        ///reject		Reject the call to the function and immediately return.
        ///		Refer to `help hook` for information about stack balancing.
        ///terminate	Terminate the client process.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Help_Verdict {
            get {
                return ResourceManager.GetString("Commands.Help.Verdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 break	- (D) Breaks or continues the process&apos;s execution. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Break {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 doll	- (M) Creates a new Doll client. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Doll {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Doll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dump	- (D) Displays or saves dumped data. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Dump {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 end	- (M/D) Ends the client, stopping its process. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_End {
            get {
                return ResourceManager.GetString("Commands.HelpShort.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eval	- (D) Evaluates a expression on current context. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Eval {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exit	- Quits the Controller, end all connected clients. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Exit {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For more information on a specific command, type `help COMMAND`.
        ///All the commands are case-sensitive.
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Header {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 help	- Provides help information for commands. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Help {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hook	- (D) Installs a new hook and set its actions. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Hook {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kill	- (M) Terminates process(es) with PID or name. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Kill {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 listen	- Starts to listen for clients. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Listen {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 load	- Executes commands from a script. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Load {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 loaddll	- (D) Loads a module into the process&apos;s address space. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_LoadDll {
            get {
                return ResourceManager.GetString("Commands.HelpShort.LoadDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ps	- (M) Displays a list of running processes. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Ps {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rem	- Records comments (remarks) in a script file. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Rem {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shell	- (M) Starts a instance of command interpreter. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Shell {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 target	- Gets or sets the target client. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Target {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unhook	- (D) Uninstalls a hook. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Unhook {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Unhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 verdict	- (D) Verdicts an activated hook. 的本地化字符串。
        /// </summary>
        internal static string Commands_HelpShort_Verdict {
            get {
                return ResourceManager.GetString("Commands.HelpShort.Verdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0,-4} {1,-18} {2} 的本地化字符串。
        /// </summary>
        internal static string Commands_Hook_Format {
            get {
                return ResourceManager.GetString("Commands.Hook.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #    OEP                Name
        ///----+------------------+------------------------- 的本地化字符串。
        /// </summary>
        internal static string Commands_Hook_Header {
            get {
                return ResourceManager.GetString("Commands.Hook.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Hook under name &quot;{0}&quot; already exists. Overwriting its settings. 的本地化字符串。
        /// </summary>
        internal static string Commands_Hook_HookExists {
            get {
                return ResourceManager.GetString("Commands.Hook.HookExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook #{0} &quot;{1}&quot; installed at {2}. 的本地化字符串。
        /// </summary>
        internal static string Commands_Hook_Installed {
            get {
                return ResourceManager.GetString("Commands.Hook.Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String incomplete. 的本地化字符串。
        /// </summary>
        internal static string Commands_Incomplete {
            get {
                return ResourceManager.GetString("Commands.Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid command `{0}`. Try `help {1}`. 的本地化字符串。
        /// </summary>
        internal static string Commands_Invalid {
            get {
                return ResourceManager.GetString("Commands.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I/O exception {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Commands_IOError {
            get {
                return ResourceManager.GetString("Commands.IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The listener has already been started. 的本地化字符串。
        /// </summary>
        internal static string Commands_Listen_AlreadyStarted {
            get {
                return ResourceManager.GetString("Commands.Listen.AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available addresses:
        /// 的本地化字符串。
        /// </summary>
        internal static string Commands_Listen_AvailableAddresses {
            get {
                return ResourceManager.GetString("Commands.Listen.AvailableAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parens mismatch. 的本地化字符串。
        /// </summary>
        internal static string Commands_ParensMismatch {
            get {
                return ResourceManager.GetString("Commands.ParensMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0,-8} {1} 的本地化字符串。
        /// </summary>
        internal static string Commands_Ps_Format {
            get {
                return ResourceManager.GetString("Commands.Ps.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID      Name
        ///--------+-------------------------------- 的本地化字符串。
        /// </summary>
        internal static string Commands_Ps_Header {
            get {
                return ResourceManager.GetString("Commands.Ps.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current target is #{0} &quot;{1}&quot; ({2}, {3}). 的本地化字符串。
        /// </summary>
        internal static string Commands_Target_CurrentTarget {
            get {
                return ResourceManager.GetString("Commands.Target.CurrentTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1,-4} {2,-32} {3,-8} {4,-8} {5,-8} {6,-4} 的本地化字符串。
        /// </summary>
        internal static string Commands_Target_Format {
            get {
                return ResourceManager.GetString("Commands.Target.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   #    Name                             Type     Status   PID      Bits
        ///-+----+--------------------------------+--------+--------+--------+---- 的本地化字符串。
        /// </summary>
        internal static string Commands_Target_Header {
            get {
                return ResourceManager.GetString("Commands.Target.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified hook does not exist. 的本地化字符串。
        /// </summary>
        internal static string Commands_Unhook_NotFound {
            get {
                return ResourceManager.GetString("Commands.Unhook.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook #{0} &quot;{1}&quot; removed. 的本地化字符串。
        /// </summary>
        internal static string Commands_Unhook_Uninstalled {
            get {
                return ResourceManager.GetString("Commands.Unhook.Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown command `{0}`. 的本地化字符串。
        /// </summary>
        internal static string Commands_Unknown {
            get {
                return ResourceManager.GetString("Commands.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 Error {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Commands_Win32Error {
            get {
                return ResourceManager.GetString("Commands.Win32Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action &quot;{0}&quot; failed: {1} 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_ActionError {
            get {
                return ResourceManager.GetString("Threads.Client.ActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New client from {0}: #{1} &quot;{2}&quot; ({3}). 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Connected {
            get {
                return ResourceManager.GetString("Threads.Client.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading register #{0}. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_ContextReadError {
            get {
                return ResourceManager.GetString("Threads.Client.ContextReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ctx: Dictionary entry created: {0} =&gt; {1}. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Ctx {
            get {
                return ResourceManager.GetString("Threads.Client.Ctx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary entry &quot;{0}&quot; not found. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_DictionaryReadError {
            get {
                return ResourceManager.GetString("Threads.Client.DictionaryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client &quot;{0}&quot; disconnected, reason: {1} 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Disconnected {
            get {
                return ResourceManager.GetString("Threads.Client.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dump: Dump #{0} created ({1} bytes). 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Dump {
            get {
                return ResourceManager.GetString("Threads.Client.Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo: {0} 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Echo {
            get {
                return ResourceManager.GetString("Threads.Client.Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client &quot;{0}&quot; hooked on #{1} &quot;{2}&quot; - phase &quot;{3}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Hooked {
            get {
                return ResourceManager.GetString("Threads.Client.Hooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Malformed libPuppet packet. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_MalformedPacket {
            get {
                return ResourceManager.GetString("Threads.Client.MalformedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading memory. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_MemoryReadError {
            get {
                return ResourceManager.GetString("Threads.Client.MemoryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Reading memory: Size expected = {0}, got = {1} 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_MemoryReadWarning {
            get {
                return ResourceManager.GetString("Threads.Client.MemoryReadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alive 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Status_Alive {
            get {
                return ResourceManager.GetString("Threads.Client.Status.Alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Status_Dead {
            get {
                return ResourceManager.GetString("Threads.Client.Status.Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hooked 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Status_Hooked {
            get {
                return ResourceManager.GetString("Threads.Client.Status.Hooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Reading string: Truncated incomplete string. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_StringReadWarning {
            get {
                return ResourceManager.GetString("Threads.Client.StringReadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Reading string: Truncated long string. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_StringTooLongWarning {
            get {
                return ResourceManager.GetString("Threads.Client.StringTooLongWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doll 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Type_Doll {
            get {
                return ResourceManager.GetString("Threads.Client.Type.Doll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Type_Monitor {
            get {
                return ResourceManager.GetString("Threads.Client.Type.Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression type mismatch. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_TypeMismatch {
            get {
                return ResourceManager.GetString("Threads.Client.TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 verdict: Executing verdict &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_Verdict {
            get {
                return ResourceManager.GetString("Threads.Client.Verdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 verdict: Waiting for verdict 的本地化字符串。
        /// </summary>
        internal static string Threads_Client_VerdictWait {
            get {
                return ResourceManager.GetString("Threads.Client.VerdictWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested operation is not applicable to the specified target. 的本地化字符串。
        /// </summary>
        internal static string Threads_CmdEngine_TargetNotApplicable {
            get {
                return ResourceManager.GetString("Threads.CmdEngine.TargetNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified target is dead or does not exist. 的本地化字符串。
        /// </summary>
        internal static string Threads_CmdEngine_TargetNotAvailable {
            get {
                return ResourceManager.GetString("Threads.CmdEngine.TargetNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile error: {0} 的本地化字符串。
        /// </summary>
        internal static string Threads_EvalEngine_CompileError {
            get {
                return ResourceManager.GetString("Threads.EvalEngine.CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty expression. 的本地化字符串。
        /// </summary>
        internal static string Threads_EvalEngine_Empty {
            get {
                return ResourceManager.GetString("Threads.EvalEngine.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot evaluate expression of type {0}. 的本地化字符串。
        /// </summary>
        internal static string Threads_EvalEngine_InvalidType {
            get {
                return ResourceManager.GetString("Threads.EvalEngine.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime exception {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Threads_EvalEngine_RuntimeError {
            get {
                return ResourceManager.GetString("Threads.EvalEngine.RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEDoll Controller v{0}
        /// 的本地化字符串。
        /// </summary>
        internal static string UI_Cli_Banner {
            get {
                return ResourceManager.GetString("UI.Cli.Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///[ Ctrl-C received, press any key to stop the engine... ] 的本地化字符串。
        /// </summary>
        internal static string UI_Cli_CtrlC {
            get {
                return ResourceManager.GetString("UI.Cli.CtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt; {0} 的本地化字符串。
        /// </summary>
        internal static string UI_Cli_Format {
            get {
                return ResourceManager.GetString("UI.Cli.Format", resourceCulture);
            }
        }
    }
}
